import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  buttonWrapper: {
    width: '100%',
    backgroundColor: '#FFFFFF',
  },
  buttonRegistrations: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 100,
    elevation: 3,
    backgroundColor: '#FF6C00',
  },
  buttonRegistrationsText: {
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#FFFFFF',
  },
  buttonLogin: {
    borderRadius: 100,
    elevation: 3,
    marginBottom: 66,
  },
  textFooterWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingVertical: 6,
    marginBottom: 32,
  },
  buttonLoginText: {
    marginRight: 5,
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#1B4371',
  },
  buttonLoginTextLink: {
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#1B4371',
    textDecorationLine: 'underline',
  },
});
