import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  formWrapper: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    minHeight: '60%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
  },

  title: {
    marginTop: 32,
    marginBottom: 33,
    fontFamily: 'Medium',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 30,
    lineHeight: 35,
    textAlign: 'center',
    letterSpacing: 0.01,
    color: '#212121',
  },
  image: {
    position: 'absolute',
    height: '100%',
    width: '100%',
  },
  loginErrorWrapper: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    marginBottom: 5,
  },
  loginErrorText: {
    fontFamily: 'Medium',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 12,
    color: 'red',
  },
  buttonWrapper: {
    width: '100%',
    backgroundColor: '#FFFFFF',
  },
  buttonLog: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 100,
    elevation: 3,
    backgroundColor: '#FF6C00',
  },
  buttonLogText: {
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#FFFFFF',
  },
  buttonReg: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 32,
    borderRadius: 100,
    elevation: 3,
  },
  buttonRegText: {
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#1B4371',
  },
  buttonRegLink: {
    fontFamily: 'Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    color: '#1B4371',
    textDecorationLine: 'underline',
  },
});
